### PR TITLE
Support perls which do not provide . in @INC by default in Build.PL

### PR DESCRIPTION
**Pull request by toddr**

### CODE REVIEW

**Comment by toddr** [comment]
This patch won't help if Build.PL is being generated. I opened this ticket to get Minilla to support @INC without . in it. https://github.com/tokuhirom/Minilla/issues/215

**Comment by toddr** [comment]
Hi, it looks like you may want to reject this patch. What is needed is for you to update to Minilla v3.0.10, which will re-generate Build.PL correctly on your next release.

Thanks!

**Comment by kazeburo** [comment]
Just released 0.24 that was packaged by Minilla 3.x

**Comment by toddr** [comment]
Thank you!!!

**Pull request closed without merging**
